# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "745883cdcaf79d7a78ee3b184b7e8eea"
application_url = "https://dozens-information-rapids-cas.trycloudflare.com"
embedded = true
name = "marketing"
handle = "marketing-26"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dozens-information-rapids-cas.trycloudflare.com/auth/callback",
  "https://dozens-information-rapids-cas.trycloudflare.com/auth/shopify/callback",
  "https://dozens-information-rapids-cas.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "cart-transform-testing-imjol.myshopify.com"
automatically_update_urls_on_dev = true
